### ISSUE TITLE
Remove key as required param for setItem

### ISSUE THREAD

**Issue by lilasquared** [dance2die/react-use-localstorage#1]
```ts
import React from "react";

export default function useLocalStorage(key: string) {
  const [item, setValue] = React.useState(() => window.localStorage.getItem(key));

  const setItem = (item: string) => {
    setValue(item);
    window.localStorage.setItem(key, item);
  };

  return [item, setItem];
}
```
this should work just fine since key is captured by the closure?

**Comment by dance2die** [comment]
Hi.@lilasquared.

`setItem` doesn't accept `key`, only an `item` as a argument.

If I misunderstood would you be able to propose a possible implementation?

**Comment by lilasquared** [comment]
https://github.com/dance2die/react-use-localstorage/blob/544523a1e80618d55c4647ad450cffc246743445/src/index.ts#L6

This is your source code where key is a parameter to setItem. The above code is the proposed implementation.

**Comment by dance2die** [comment]
Thanks @lilasquared~ 👍

That makes sense and easier to use. I thought the code you had posted initially was my own implementation 😅

I will update the code with updated version number.

**Comment by dance2die** [comment]
@lilasquared I've updated the major version (now at v2.2.0 😉 after fixing some issues) as it was a breaking change.

I've also fixed some issues where form fields were [uncontrolled initially](https://github.com/dance2die/react-use-localstorage/commit/a00b55d9581a7db0073f4037cc3a0a92ba8b5954).

**Comment by dance2die** [comment]
@all-contributors please add @lilasquared for ideas

**Comment by dance2die** [comment]
@all-contributors please add @dance2die for code, bug, doc
