### ISSUE TITLE
Use JSON.parse/stringify to accept any value (not just strings)

### ISSUE THREAD

**Issue by FezVrasta** [dance2die/react-use-localstorage#15]
Thanks for the hook!

It'd be great if you used JSON.parse & JSON.stringify to store and read values from localstorage, doing so the value could be anything, not just strings.

**Comment by dance2die** [comment]
Thank you for the suggestion @FezVrasta 🙂

I've initially thought about adding JSON parse but didn't include it for two reasons.
1. Keep the API as close to that of `localStorage`.
1. Want to keep code small by removing `JSON.*` methods.

But you just gave me a new hook idea for your suggestion
_`react-use-storage`? 😋_ (which would work for both/either `localStorage/sessionStorage` as this one works with `localStorage` only)

**Comment by remi2j** [comment]
Why not adding it to this library?

**Comment by dance2die** [comment]
@remi2j That's good question 🙂

It's due

1. to keep each library light (one tool for one job) .
2. to stay consistent with LocalStorage API
3. to create flexible (local/session/cookie storage) library with object support 
    - In this case, the name (react-use-localstorage) would not do what the name says it does.

I intend to keep the new library in the same repo, which I created here.  
https://github.com/dance2die/react-use-localstorage/tree/monorepo

Let me know if you have more questions~✨

**Comment by dance2die** [comment]
OK, I've found [react-use-storage](https://www.npmjs.com/package/react-use-storage) library, which looks great.

I won't be writing the same library as 👆 looks great supporting both `local/sessionStorage` and sync data when it is changed elsewhere
