### ISSUE TITLE
Discuss: Read from and write to localStorage

### ISSUE THREAD

**Issue by SeanMcP** [dance2die/react-use-localstorage#21]
When calling `useLocalStorage()`, the library is reading the value from `localStorage` if it exists. When calling the setter function, the data is updated in `localStorage`.

After the initial call, the library is attempting to maintain two pieces of data in sync: the value returned from `useState()`, and the value in `localStorage`. Essentially, there are two sources of truth.

If there is a problem setting or getting data from `localStorage`, the library will still return the value from `useState()` despite the error. In this instance, the user would assume that their data is saved in `localStorage`, but in actually the library is just storing it in state.

What if instead the library wrote to and read from `localStorage` directly? There would be a single source of truth instead of two. I'm imagining something similar to [this example on from usehooks.com](https://usehooks.com/useLocalStorage).

A potential drawback is speed: setting `localStorage` is a relatively slow process. But I think the benefits will outweigh the cost.

**Comment by dance2die** [comment]
> there are two sources of truth. [...] in actually the library is just storing it in state.

That's a great point I've never considered initially.

> What if instead the library wrote to and read from localStorage directly?

`useState` value (`state` hereafter) will be out of sync when used in multiple components creating an issue. Having `localStorage` as one single source of truth would help on sync'ing `states`.

Currently it'd require firing an event on `setValue` to keep each `state` in sync in multiple `useLocalStorage` calls in other components but having the source of truth on `localStorage` would not require such hack.

So I am for having `localStorage` as the only source of truth.

> A potential drawback is speed: setting localStorage is a relatively slow process. But I think the benefits will outweigh the cost.

What would you think about implementing `setValue` to return a promise work? (as opposed to the synchronous implementation from usehooks.com)

It'd break the backwards compatibility (major version change) but so long as it provides a better 
 experience I find it worth it

**Comment by SeanMcP** [comment]
> What would you think about implementing setValue to return a promise work?

I've never used state hooks and promises together before. What would that look like?

**Comment by SeanMcP** [comment]
@dance2die I put together a [CodeSandbox with a working prototype](https://codesandbox.io/s/spike-react-use-localstorage-y541g) (without promises). It supports objects as passed values, too.

With a single text input, there isn't a noticeable difference in speed.

**Comment by dance2die** [comment]
> If there is a problem setting or getting data from localStorage, the library will still return the value from useState() despite the error. 

In this scenario,

```jsx
  function setter(value) {
    try {
      set(key, value);
      setValue(get(key));
    } catch (err) {
      console.log(`Error setting \`${key}\` on \`localStorage\`:`, err);
    }
  }
```
Wouldn't localStorage value be out of sync when it fails at `setValue(get(key))`?

In the current version, user sets a state value using a native React's dispatch method returned from `useState`. Then the effect is run as the effect depends on the `[value]`.

```jsx
  React.useEffect(() => {
    localStorage.setItem(key, value);
  }, [value]);`
```

Wouldn't current implementation have the same implication (useState value & localStorage value being out of sync)?

I think the proposed implementation has the same out-of-sync issue if the localStorage is the point of failure 🤔

And I am for storing data as object (instead of putting a burden on the caller to de/serialize using `JSON.stringify/parse` 🙂

**Comment by SeanMcP** [comment]
You're right; if `set()` works but `get()` somehow fails, then we will be out of sync. But I can't think of a scenario where that would happen. `localStorage.setItem()` and `localStorage.getItem()` will only catch if you pass no arguments, which isn't possible here because we're controlling that.
