### ISSUE TITLE
Error when using server-side rendering (SSR)

### ISSUE THREAD

**Issue by haydn** [dance2die/react-use-localstorage#24]
## Overview

This hook currently throws this error when used with `ReactDOMServer`:

```
ReferenceError: window is not defined
    at eval (webpack:///./node_modules/react-use-localstorage/dist/react-use-localstorage.esm.js?:12:5)
```

This happens because it's trying to access `window` when getting the initial value ([runpkg link](https://runpkg.com/?react-use-localstorage@3.2.0/dist/react-use-localstorage.esm.js)):

https://github.com/dance2die/react-use-localstorage/blob/af1c0b724613096be1b79bcb830b8dea0137cd09/src/index.ts#L7-L9

**Note**: The function that is passed to `useEffect` isn't executed on a server, so accessing `window` there doesn't cause any problems.

## Expected Behaviour

The `initialValue` is always used when rendering on the server.

## Current Behaviour

It throws an error.

## Workaround

An easy way to workaround this issue is to wrap it in a custom hook:

```js
const useSSRLocalStorage = (key, initial) =>
  typeof window !== "undefined" ? useLocalStorage(key, initial) : [initial];
```

**Comment by dance2die** [comment]
Hi @haydn Thanks for the SSR issue and the workaround for it.

I think the implementation of `useSSRLocalStorage` might be better to be mentioned in the README instead of adding it to the library as it's so simple and probably not used all the time.

**Comment by hencatsmith** [comment]
Just leaving a quick drive-by comment to thank @haydn for the workaround for this issue. I'm using this hook in a Gatsby project where all components need to be SSR safe and it fixed my problem!

**Comment by dance2die** [comment]
#34 to associate the issue.

**Comment by otherjohn** [comment]
PLEASE PLEASE PLEASE reference this fix for Gastby users. I spent days trying to track down what was happening. @haydn  and @hencatsmith (I use Typescript) fix was great for my Gastby build error!

**Comment by dance2die** [comment]
Hi @otherjohn.

I've updated README with @hencatsmith's workaround

**Comment by Aditya94A** [comment]
Where exactly should you put this useSsr hook?

I get the following error:

```
 React Hook "useLocalStorage" is called conditionally. React Hooks must be called in the exact same order in every
 component render  react-hooks/rules-of-hooks
```

**Comment by haydn** [comment]
@AdityaAnand1 Ah, yes. That linter is probably upset that we're calling `useLocalStorage` inside a conditional, which is technically [against the rules](https://reactjs.org/docs/hooks-rules.html). In practice this isn't actually going to be a problem because the condition isn't going to change between updates (it's always going to one condition on the server and the other condition on the client).

A workaround for now would be to disable the ESLint rule:

```jsx
const useSSRLocalStorage = (key, initial) =>
  typeof window !== "undefined" ? useLocalStorage(key, initial) : [initial]; // eslint-disable-line react-hooks/rules-of-hooks
```

@dance2die This might be a reason to solve the problem inside the hook instead of leaving it to users to workaround it. SSR is becoming a lot more common with things like Gatsby and Next.js rising in popularity, so I think you're going to keep seeing people run into this.

**Comment by westprophet** [comment]
`const useSSRLocalStorage = (key, initial) =>
  typeof window !== "undefined" ? useLocalStorage(key, initial) : [initial]; // eslint-disable-line react-hooks/rules-of-hooks`
![image](https://user-images.githubusercontent.com/39632635/103155619-1ce95c00-47aa-11eb-99fd-2a87962f5907.png)

This code doesn't work for Next.js ^ 10. Any way, I could not apply it although I really wanted to.

**Comment by westprophet** [comment]
If anyone can help suggest how to apply this hook in next.js so that it works, I would be very grateful
