### ISSUE TITLE
New feature -> watch localstorage??

### ISSUE THREAD

**Issue by intergalactic-overlords** [dance2die/react-use-localstorage#27]
Hi, I was using your module (thanks by the way :-) ) and I encountered a problem. I was in a situation where one component was updating localstorage and another one was 'watching' it. And if localstorage was updated, the watching component needed to rerender with the new data.
But the way the hook is written, it doesn't 'watch' localstorage.

So in my project, I modified your hook and added the following effect:
```
  useEffect(() => {
    const checkValue = localStorage.getItem(key)
    if (checkValue  !== value) {
      setValue(checkValue )
    }
  });
```
This way, the state is updated when localstorage changes, and each component using the hook rerenders with the new data. For me it works perfectly, but perhaps you might see a downside (besides added complexity and extra calls to localStorage).
It could also be hidden behind an option.

So anyhow, do want you want with it :-) but I just wanted to let you know what I've done to solve my problem :-)

**Comment by dance2die** [comment]
Thank you for the nice suggestion/find @intergalactic-overlords 👍 

Could you do a PR for the code & add a test for it?
because that does make the value in sync 😄
