### ISSUE TITLE
window.localstorage updated after value managed by useLocalStorage

### ISSUE THREAD

**Issue by edorivai** [dance2die/react-use-localstorage#29]
We'd been using this hook for a while, but it broke our setup after #16 was merged (we updated a couple of months after the merge).

Specifically, we perform user authentication, and save the `authToken` in `localStorage` using this hook. Now setting the `authToken` triggers a rerender in our tree, which sees that the `value` managed by `useLocalStorage` has been set, which triggers a request to be sent out using the apollo client.

Our authentication setup is configured with an apollo link which sets the `Authorization` header based on the `authToken` in localStorage. This is where our setup breaks down. While the token _is_ set in our React state tree (which causes the request to be fired in the first place), the token hasn't actually been persisted to `localStorage` yet.

Due to the way `useEffect` works, this hook only persists to `localStorage` in the _next_ render cycle.

**Comment by dance2die** [comment]
Thanks for opening up the issue @edorivai.
That indeed is a problem as the `localStorage` value is set in the _next_ render cycle and haven't considered while making the change.

I will revert it to the previous implementation, as it'd set the localStorage value on the time it's called.

**Comment by dance2die** [comment]
I've reverted the implementation and should be available in v3.3.1.  
https://www.npmjs.com/package/react-use-localstorage/v/3.3.1

Can you review your site and close this issue if everything's fine?

**Comment by edorivai** [comment]
Thanks, will test it on Monday!

**Comment by edorivai** [comment]
@dance2die I'm afraid I'm still seeing `useEffect` in version `3.3.1`. My original bug also still exists after updating, so that confirms it.

![image](https://user-images.githubusercontent.com/765358/67667901-2b05d780-f96f-11e9-9f25-179d86261220.png)

![image](https://user-images.githubusercontent.com/765358/67667914-322ce580-f96f-11e9-8904-2bef969d76f1.png)

**Comment by dance2die** [comment]
@edorivai 
I am sorry It looks like I didn't build before publishing.  
I've added a [script to build before publish](https://github.com/dance2die/react-use-localstorage/blob/master/package.json#L22) so it won't happen again.

Below is the v3.3.2 available now.
https://unpkg.com/browse/react-use-localstorage@3.3.2/dist/react-use-localstorage.esm.js

```javascript
import { useState } from 'react';

function useLocalStorage(key, initialValue) {
  if (initialValue === void 0) {
    initialValue = '';
  }

  var _useState = useState(function () {
    return localStorage.getItem(key) || initialValue;
  }),
      value = _useState[0],
      setValue = _useState[1];

  var setItem = function setItem(newValue) {
    setValue(newValue);
    window.localStorage.setItem(key, newValue);
  };

  return [value, setItem];
}

export default useLocalStorage;
//# sourceMappingURL=react-use-localstorage.esm.js.map
```

**Comment by edorivai** [comment]
Confirmed! :tada:

**Comment by vidjuheffex** [comment]
I'm still seeing this behavior... I reverted to 3.3.2 to solve this for myself... is this expected? I can't use the latest versions because initial value isn't set into local storage
