### ISSUE TITLE
Question: react strictMode

### ISSUE THREAD

**Issue by dimaqq** [dance2die/react-use-localstorage#31]
When running in development with `strictMode` set, components that use hooks are rendered twice.

I've just ran into that implementing something like `react-use-localstorage` manually.
The naïve solution is to isolate `setItem()` into an effect.

In my case, the issue became visible when my code looked like:
```
const Comp = () => {
  const state = localeStorage.getItem(...);
  if (cond1) {
    localStorage.setItem(...);
    return <.../>;
  }
  
  if (cond2) {
    localStorage.setItem(...);
    return <.../>;
  }
};
```

Because react rendered the component twice, there was a case where `cond1` and `cond2` appeared to be in effect simultaneously (one during first render, the other during second render).

I wonder if using this library I'm bound to run into the same problem.

**Comment by dance2die** [comment]
Hi @dimaqq. I don't quite understand the following statement.

> there was a case where cond1 and cond2 appeared to be in effect simultaneously (one during first render, the other during second render).

Would it be more of checking whether to update states within `useEffect` depending on `cond1` or `cond2` conditions?

Could you provide a a small sample on CodeSandbox.io or StackBlitz.com what the code might look like?

**Comment by dimaqq** [comment]
I’ve decided not to use this library.
Ultimately reading local storage in redux init made more sense for me. That plus use effect and now I don’t need to worry about double render in strict mode.
