### ISSUE TITLE
Synchronize localStorage values between components

### ISSUE THREAD

**Issue by hug0b** [dance2die/react-use-localstorage#35]
I was expecting this hook would synchronize values between components after reading the code and seeing https://github.com/dance2die/react-use-localstorage/issues/27 but it doesn't seem to work.

Demo : https://codesandbox.io/s/synchronize-localstorage-h8cg7

Update: I am currently using [react-hooks-global-state](https://github.com/dai-shi/react-hooks-global-state/tree/master/examples/13_persistence) to achieve this. [use-persisted-state](https://github.com/donavon/use-persisted-state) seems work in a similar fashion ?

**Comment by astoilkov** [comment]
I have written https://github.com/astoilkov/use-local-storage-state which solves this problem. You can try it out.

**Comment by dance2die** [comment]
@astoilkov Nice one there.

I am thinking about deprecating this library, or hand it off to someone as I am not maintaining it nowadays.

**Comment by astoilkov** [comment]
This module comes up first when searching for "use local storage" so it

**Comment by astoilkov** [comment]
Thanks for the words @dance2die. 

This module comes up first when searching for "use local storage" on npmjs.org so it would be great to do something with it and help the users searching for a solution.
