### ISSUE TITLE
How to remove data from local storage?

### ISSUE THREAD

**Issue by uladkasach** [dance2die/react-use-localstorage#36]
After writing to local storage, is it possible to remove a key from it? I would like to delete the data I had persisted for a user in localstorage.

**Comment by dance2die** [comment]
`localStorage.removeItem` would remove the key-value from local storage.  
https://developer.mozilla.org/en-US/docs/Web/API/Storage/removeItem

So simply call `localStorage.removeItem('myKey');` to remove.

**Comment by uladkasach** [comment]
oh wow, simple as that. thank you very much!

**Comment by hanvyj** [comment]
Would be nice to be able to use the same interface and `setItem(undefined)`.

**Comment by dance2die** [comment]
> Would be nice to be able to use the same interface and `setItem(undefined)`.

Wouldn't work as local storage wouldn't know which key to delete. :wink:   
Even if you would do `setItem(key, undefined)`, a dev might want to have the key available.
