### ISSUE TITLE
useEffect without dependencies that call useState

### ISSUE THREAD

**Issue by jrmi** [dance2die/react-use-localstorage#39]
![image](https://user-images.githubusercontent.com/571533/84819104-c7bcd880-b017-11ea-90ee-b1d122ed81f0.png)

**Comment by jrmi** [comment]
![image](https://user-images.githubusercontent.com/571533/84819261-02267580-b018-11ea-8c45-373c9d2a4795.png)

**Comment by dance2die** [comment]
Thanks for the issue, @jrmi.

Do you have steps to reproduce it? A codesandbox/stackblitz, or a repo I can check out?

**Comment by jrmi** [comment]
I'll try to do something.

**Comment by tmm1** [comment]
@jrmi any update on a repro?

**Comment by dance2die** [comment]
I am sorry @jrmi.

My attention hasn't been on this &  
I will be looking for one to take over this project.

**Comment by jrmi** [comment]
I'm also sorry, I was busy with other projects as well. I tried to reproduce it alone outside of my project, but I think there is a conflict with something a doesn't manage to reproduce alone. 

If nobody had the same issue, I'm ok to close it since I can't be sure this was the source of my problem. Sorry for that.
