### ISSUE TITLE
Wrong peer dependency

### ISSUE THREAD

**Issue by evgenymarkov** [dance2die/react-use-localstorage#40]
Hi! Your library has wrong react version in peer dependency (^16.10.2 instead of 16.8.1+). Please fix it.
You can also prepare the library for the React 17 release. Thanks.

**Comment by dance2die** [comment]
Thanks @evgenymarkov.   
I will fix it and any reason for 16.8.1 instead of 16.8.0?

> You can also prepare the library for the React 17 release

Would you mean create an experimental branch for React 17?

**Comment by evgenymarkov** [comment]
> I will fix it and any reason for 16.8.1 instead of 16.8.0?

I don't know any reasons why library should depend on 16.8.1 instead of 16.8.0 :) I saw this version in README.

<img width="393" alt="image" src="https://user-images.githubusercontent.com/16443248/90827733-6da50000-e345-11ea-8850-e211f9309380.png">

> Would you mean create an experimental branch for React 17?

I mean, you can support React 17 version in peerDependencies too.

**Comment by dance2die** [comment]
Thank you, @evgenymarkov.
It was my mistake as I updated it using `npm-check-updates`...

I've downgraded while updating other packages (notibly tsdx and typescript to version 4.0.2).  
Published package.json: https://unpkg.com/browse/react-use-localstorage@3.4.5/package.json

> I mean, you can support React 17 version in peerDependencies too.

Any implications on having multiple version of React as peer dependencies?

**Comment by evgenymarkov** [comment]
> Any implications on having multiple version of React as peer dependencies?

I think you can set React version to >=16.8.1:

```json
"peerDependencies": {
  "react": ">=16.8.1"
},
```

Your library will work on any version of React that supports hooks. Warnings will stop when installing library.

**Comment by dance2die** [comment]
Oh Yikes~ I've never used `>=` for the deps!  
Thank you for the help and I've updated the peer deps.  
https://unpkg.com/browse/react-use-localstorage@3.5.3/package.json

NPM blog also shows

> If you depend on features introduced in 1.5.2, use ">= 1.5.2 < 2".
> - https://nodejs.org/es/blog/npm/peer-dependencies/

**Comment by dance2die** [comment]
@all-contributors please add @evgenymarkov for bug and ideas

**Comment by evgenymarkov** [comment]
I will update the library in my projects. Thank you very much!

**Comment by dance2die** [comment]
:confetti_ball: Hooray. You're welcome and thank you for helping out~
