### ISSUE TITLE
Where I can find changelog?

### ISSUE THREAD

**Issue by Aspedm** [dance2die/react-use-localstorage#42]
I use 3.4.3 version, current version 3.5.3 released 9 days ago. Where I can find changes between versions?
CHANGELOG.md - not found
tags - empty description 
readme - not found changelog

thx.

**Comment by dance2die** [comment]
Good question @Aspedm.

There is no Changelog... :sweat: 

The plan was to use [conventional-changelog/conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) and never had change to implement it.

Would that be suitable for your needs if implemented?

**Comment by Aspedm** [comment]
Any solution is better than now :)

**Comment by dance2die** [comment]
not stale
