### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by saeedhemmati** [dance2die/react-use-localstorage#49]
Hi
While using **react-use-localstorage** in nextjs i got this error:
`SyntaxError: Cannot use import statement outside a module`

I use this [approache](https://github.com/dance2die/react-use-localstorage/issues/24#issuecomment-581479939) for using of this module in nextjs as SSR.

I would be appreciate for resolve this issue

node: v 14.17.0
npm: v 6.14.13
Operating system: linux-kubuntu 20.04

**Comment by dance2die** [comment]
Hi @saeedhemmati.

Refer to the note in README.
https://github.com/dance2die/react-use-localstorage#note-for-ssr-server-side-rendering

**Comment by highflying** [comment]
I have the same issue as this and I'm using the fix noted in the README.

**Comment by zwily** [comment]
I also have this issue. The problem appears to be happening at import time, which the workaround doesn't do anything about.
