### ISSUE TITLE
useLocalstorage doesnt sync between components

### ISSUE THREAD

**Issue by ilovett** [dance2die/react-use-localstorage#51]
I am trying using the exact same key across multiple components and they do not sync.  Click "INCREMENT" in the demo and see that only the root `useLocalstorage` updates.

https://codesandbox.io/s/usevisibilitysensor-forked-c70ww

Side Note:  The `useLocalstorage` demo on the docs points to useVisibilitySensor demo

**Comment by AlexLeung** [comment]
Looks like the hook doesn't even check localstorage for updates. What a useless library
