### ISSUE TITLE
Support passing object as initial value

### ISSUE THREAD

**Issue by fkrafi** [dance2die/react-use-localstorage#54]
Want to support object as initial value. Example:

```
  const [item, setItem] = useLocalStorage('name', {key: 'value'});
```
then `item` value should be an object also

**Comment by fkrafi** [comment]
@dance2die, @lilasquared, @TheAifam5 , @SeanMcP , @VitorLuizC, @evgenymarkov, 

can you please verify this PR

**Comment by TheAifam5** [comment]
Hey,

thank you for submitting a PR, I will join the code review shortly.

LocalStorage natively does not support complex types such objects or arrays, from my perspective it will add additional complexity of handling and identifying such types. It would be a better option to make an extension to isolate them, new npm package or just an utility functions.

I personally like the idea despite my concerns, but it's not up to me to decide.

PS. Please don't ping everyone :) It's 00:45 AM GMT+1 and not everyone will have time to respond in 1h after submission. 

Best regards and stay safe,
TheAifam5

**Comment by lilasquared** [comment]
This is my go to lib for lots of hooks. This one already supports complex objects via serialization. https://github.com/streamich/react-use/blob/master/src/useLocalStorage.ts

**Comment by TheAifam5** [comment]
@lilasquared oh, this looks very nice, giving a user way to set it's own serializer/deserializer in a simple manner and way to disable serialization if needed (storing arbitrary data from different sources where serialization/deserialization is not required).
