### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by zkhalapyan** [dance2die/react-use-localstorage#57]
1. npm install 
2. `import useLocalStorage from 'react-use-localstorage';` 
3. Notice error below:

I can't update my `package.json`'s type to be `module`, since this breaks next.js

<img width="998" alt="Screen Shot 2022-02-07 at 3 28 31 PM" src="https://user-images.githubusercontent.com/796815/152889490-e476381d-b18d-48c1-aa67-8c576fad6a12.png">

**Comment by letterpaulsand** [comment]
maybe you can write it on the useeffect the react hook
